### ISSUE TITLE
Error: "Please add an alias for "google-chrome" to your CLI environment."

### ISSUE THREAD

**Issue by loopy3025** [docksal/drupal7-advanced#10]
I've been trying to follow the instructions for using Behat and Docksal. The site fires up in our regular browser just fine, but after I include selenium in the Docksal yml file, the driver is included, but behat still can't find Chrome.  

![image](https://user-images.githubusercontent.com/6729935/38376261-37d0edee-38c6-11e8-9b9f-37c8723d3a90.png)

Have I configured the behat.yml wrong?

```
# Docker profile.
# For use inside the CLI container in Docksal.
docker:
  extensions:
    Behat\MinkExtension:
      # URL of the site when accessed inside Docksal.
      base_url: http://web
      # Configure browser to be used. Browser must be available on wd_host.
      # Stick with chrome by default. It's 2x faster than firefox or phantomjs (your results may vary).
      browser_name: chrome
      selenium2:
        wd_host: http://browser:4444/wd/hub
        capabilities: { "browser": "chrome", "version": "*" }
    Drupal\DrupalExtension:
      drupal:
        # Site docroot inside Docksal.
        drupal_root: /var/www/docroot
      drush:
        # Site docroot inside Docksal.
        root: /var/www/docroot
default:
  suites:
    default:
      paths:
        - %paths.base%/features
  extensions:
    Behat\MinkExtension:
      default_session: goutte
      browser_name: chrome
      javascript_session: default
      goutte: ~
      files_path: "%paths.base%/media"
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: "drupal"
    jarnaiz\JUnitFormatter\JUnitFormatterExtension:
        filename: report.xml
        outputDir: %paths.base%/build/tests
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_steps
      image_drivers:
        local:
          screenshot_directory: /tmp

```
Note that this is a BLT-built Drupal instance.

Thanks for any help you can provide.
